## 🧩 Understanding np.zeros_like in NumPy
np.zeros_like is a NumPy function that creates a new array filled with zeros, having the same shape and type as another given array.

## 📌 Syntax

``` python
numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
```

## ⚡ Parameters

* **a** → The reference array. The new array will copy its shape and type.
* **dtype (optional)** → Specify a different data type for the new array.
* **order (optional)** → Memory layout ('C' for row-major, 'F' for column-major).
* **subok (optional)** → If True, subclasses are preserved.
* **shape (optional)** → Override the shape of the new array.
                                  

## 🎯 What It Does

* Creates an array of zeros.
* Matches the shape and data type of the input array (unless overridden).
* Useful when you want a zero-initialized array that mirrors another array’s structure.


## 🧩 Example

In [1]:
import numpy as np

# Original array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Create zeros with same shape and type
zeros_arr = np.zeros_like(arr)

print("Original:\n", arr)
print("\nZeros_like:\n", zeros_arr)


Original:
 [[1 2 3]
 [4 5 6]]

Zeros_like:
 [[0 0 0]
 [0 0 0]]
